<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52011" started-at="2018-06-22T10:37:07Z" finished-at="2018-06-22T10:37:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="52011" started-at="2018-06-22T10:37:07Z" finished-at="2018-06-22T10:37:59Z">
      <class name="Execution.Login">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Execution.Login@27c20538]" name="beforeTest" is-config="true" duration-ms="1713" started-at="2018-06-22T16:07:07Z" finished-at="2018-06-22T16:07:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="Validate_data_For_Teacher(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="Validate_data_For_Teacher" duration-ms="9875" started-at="2018-06-22T16:07:10Z" data-provider="Login_For_Teacher" finished-at="2018-06-22T16:07:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[salil]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[sharma]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at Execution.Login.Validate_data_For_Teacher(Login.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_data_For_Teacher -->
        <test-method status="FAIL" signature="Validate_data_For_Teacher(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="Validate_data_For_Teacher" duration-ms="5514" started-at="2018-06-22T16:07:20Z" data-provider="Login_For_Teacher" finished-at="2018-06-22T16:07:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at Execution.Login.Validate_data_For_Teacher(Login.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_data_For_Teacher -->
        <test-method status="FAIL" signature="Validate_data_For_Teacher(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="Validate_data_For_Teacher" duration-ms="4687" started-at="2018-06-22T16:07:25Z" data-provider="Login_For_Teacher" finished-at="2018-06-22T16:07:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ok]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Something is wrong as for wrong email or password no message is visible expected [Shows Erro] but found [Shows Error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at Execution.Login.Validate_data_For_Teacher(Login.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_data_For_Teacher -->
        <test-method status="PASS" signature="Validate_data_For_Teacher(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="Validate_data_For_Teacher" duration-ms="7595" started-at="2018-06-22T16:07:30Z" data-provider="Login_For_Teacher" finished-at="2018-06-22T16:07:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2323232323]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Test@1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_data_For_Teacher -->
        <test-method status="PASS" signature="validate_data_For_Student(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="validate_data_For_Student" duration-ms="4772" started-at="2018-06-22T16:07:38Z" data-provider="Login_For_Student" finished-at="2018-06-22T16:07:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[salil]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[sharma]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_data_For_Student -->
        <test-method status="PASS" signature="validate_data_For_Student(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="validate_data_For_Student" duration-ms="4729" started-at="2018-06-22T16:07:42Z" data-provider="Login_For_Student" finished-at="2018-06-22T16:07:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_data_For_Student -->
        <test-method status="PASS" signature="validate_data_For_Student(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="validate_data_For_Student" duration-ms="4355" started-at="2018-06-22T16:07:47Z" data-provider="Login_For_Student" finished-at="2018-06-22T16:07:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ok]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_data_For_Student -->
        <test-method status="PASS" signature="validate_data_For_Student(int, java.lang.String, java.lang.String)[pri:0, instance:Execution.Login@27c20538]" name="validate_data_For_Student" duration-ms="6994" started-at="2018-06-22T16:07:51Z" data-provider="Login_For_Student" finished-at="2018-06-22T16:07:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8764345115]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Test@1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_data_For_Student -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Execution.Login@27c20538]" name="afterClass" is-config="true" duration-ms="542" started-at="2018-06-22T16:07:58Z" finished-at="2018-06-22T16:07:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:Execution.Login@27c20538]" name="aftertest" is-config="true" duration-ms="97" started-at="2018-06-22T16:07:59Z" finished-at="2018-06-22T16:07:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- Execution.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
